### ISSUE TITLE
Cant install qTox by Brew in OS X Yosemite

### ISSUE THREAD

**Issue by HagamosVideojuegos** [ReDetection/homebrew-qtox#7]
Shell Command: brew install --HEAD ReDetection/qtox/qtox

LOG:

==> Installing qtox from redetection/homebrew-qtox
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning git://github.com/tux3/qTox
Updating /Library/Caches/Homebrew/qtox--git
==> Checking out branch master
==> qmake
==> make
    return QString().setNum(size / pow(1024, exp),'f', exp > 1 ? 2 : 0).append(suffix[exp]);
                                   ^
4 errors generated.
make: *** [filetransferwidget.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/redetection/homebrew-qtox/issues

**Comment by ReDetection** [comment]
Hey @HagamosVideojuegos, please try again. Installation should work fine now :smile:
