### ISSUE TITLE
Merge into official repo

### ISSUE THREAD

**Issue by urras** [ReDetection/homebrew-qtox#9]
In the future, would you like to merge this formulae into the official Tox Homebrew repo at https://github.com/Tox/homebrew-tox?

**Comment by ReDetection** [comment]
Yes, somewhen in the future I would. But when it happen, I will no longer keep it working, so tox team should. 
ATM I have interest to do it by myself

**Comment by ReDetection** [comment]
So two variants: either toxteam asks me to merge this into official repo, or I wish to stop maintaining. 
Have I answered your question, @urras?

**Comment by urras** [comment]
Yes, thank you.
